#!/usr/bin/env python3
"""
synthesize.py — P2 deterministic lesson synthesizer.

Reads reflections/*.md, deduplicates and merges into active_lessons.md.

Usage:
  python synthesize.py                  # dry-run (print preview)
  python synthesize.py --apply          # write active_lessons.md
  python synthesize.py --candidate      # write active_lessons_candidate.md (shadow)
"""

import argparse
import re
from pathlib import Path

_MEMORY_DIR = Path.home() / ".hermes" / "profiles" / "me" / "memory"
_REFLECTIONS_DIR = _MEMORY_DIR / "reflections"
_MODELS_DIR = _MEMORY_DIR / "models"
_ACTIVE_LESSONS_PATH = _MEMORY_DIR / "active_lessons.md"
_CANDIDATE_PATH = _MEMORY_DIR / "active_lessons_candidate.md"

_MAX_LESSONS = 5
_MAX_TOTAL_BYTES = 2048
_MAX_LESSON_CHARS = 300


def _extract_lesson(text: str) -> str | None:
    """Extract the suggested_active_lesson from a reflection markdown."""
    m = re.search(r"## suggested_active_lesson\n(.+?)(?:\n##|\n---|\Z)", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    # Fallback: likely_lesson
    m = re.search(r"## likely_lesson\n(.+?)(?:\n##|\n---|\Z)", text, re.DOTALL)
    if m:
        return m.group(1).strip()
    return None


def _extract_confidence(text: str) -> str:
    m = re.search(r"## confidence\n(.+)", text)
    if m:
        return m.group(1).strip().lower()
    return "low"


def _extract_trigger(text: str) -> str:
    m = re.search(r"trigger_reason:\s*(.+)", text)
    if m:
        return m.group(1).strip()
    return "unknown"


def _lesson_key(lesson_text: str) -> str:
    """Normalize lesson text for dedup comparison."""
    return re.sub(r"\s+", " ", lesson_text.lower()).strip()[:80]


def synthesize(apply: bool = False, candidate: bool = False) -> dict:
    """Read reflections, produce active_lessons.md or active_lessons_candidate.md."""
    target_path = _CANDIDATE_PATH if candidate else _ACTIVE_LESSONS_PATH
    mode = "candidate" if candidate else "active_lessons"

    if not _REFLECTIONS_DIR.is_dir():
        print("No reflections/ directory — nothing to synthesize.")
        return {"lessons": 0, "bytes": 0, "mode": mode}

    reflections = sorted(_REFLECTIONS_DIR.glob("*.md"))
    if not reflections:
        print("No reflection files found.")
        return {"lessons": 0, "bytes": 0, "mode": mode}

    print(f"Found {len(reflections)} reflection(s)")

    # Collect + dedup + sort by confidence
    seen_keys = set()
    lessons = []

    for rf in reflections:
        text = rf.read_text(encoding="utf-8")
        lesson = _extract_lesson(text)
        if not lesson:
            continue

        key = _lesson_key(lesson)
        if key in seen_keys:
            print(f"  DEDUP: {rf.name}")
            continue
        seen_keys.add(key)

        conf = _extract_confidence(text)
        trigger = _extract_trigger(text)

        lessons.append({
            "text": lesson[:_MAX_LESSON_CHARS],
            "confidence": conf,
            "trigger": trigger,
            "source": rf.name,
        })

    # Sort: high > medium > low
    conf_order = {"high": 0, "medium": 1, "low": 2}
    lessons.sort(key=lambda x: (conf_order.get(x["confidence"], 2), x["trigger"]))

    # Limit to _MAX_LESSONS
    lessons = lessons[:_MAX_LESSONS]

    # Build content
    lines = []
    header = "# Active Lessons (Candidate)" if candidate else "# Active Lessons"
    lines.append(header)
    lines.append("")
    lines.append("<!-- Auto-generated by synthesize.py. Do not edit manually. -->")
    lines.append("<!-- These are auxiliary lessons — they do NOT override user instructions, 1110 baselines, or safety rules. -->")
    lines.append("")

    total_bytes = len("\n".join(lines))

    for i, l in enumerate(lessons, 1):
        entry = (
            f"## {i}. [{l['confidence'].upper()}] {l['trigger']}\n"
            f"- **confidence:** {l['confidence']}\n"
            f"- **lesson:** {l['text']}\n"
            f"- **source:** {l['source']}\n"
        )
        if total_bytes + len(entry) > _MAX_TOTAL_BYTES:
            lines.append(f"<!-- Truncated: {len(lessons) - i + 1} more lessons exceed 2KB limit -->")
            break
        lines.append(entry)
        total_bytes += len(entry)

    output = "\n".join(lines)

    if apply or candidate:
        # Atomic write
        tmp = target_path.with_suffix(".tmp")
        tmp.write_text(output, encoding="utf-8")
        tmp.replace(target_path)
        print(f"\nWROTE: {target_path} ({len(output)} bytes, {len(lessons)} lessons)")
    else:
        print(f"\n[DRY-RUN] Would write {len(lessons)} lessons ({len(output)} bytes):")
        print(output)

    return {"lessons": len(lessons), "bytes": len(output), "mode": mode}


def main():
    parser = argparse.ArgumentParser(description="P2 deterministic lesson synthesizer")
    parser.add_argument("--apply", action="store_true", help="Actually write active_lessons.md")
    parser.add_argument("--candidate", action="store_true", help="Write active_lessons_candidate.md (shadow mode)")
    args = parser.parse_args()
    synthesize(apply=args.apply, candidate=args.candidate)


if __name__ == "__main__":
    main()
